// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
part of 'app_database.dart';
// *** The actual code below is generated by drift_dev via build_runner ***
// Run: dart run build_runner build --delete-conflicting-outputs
